# Generated by Django 5.1.4 on 2024-12-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bale',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eitaa',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
