# Generated by Django 5.1.4 on 2025-02-11 06:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tire Categories',
                'db_table': 'tire_categories',
            },
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Training Categories',
                'db_table': 'training_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('IN_WAREHOUSE', 'In Warehouse'), ('IN_USE', 'In Use'), ('DISPOSED', 'Disposed')], default='IN_WAREHOUSE', max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('working_hours', models.PositiveIntegerField(default=0)),
                ('tread_depth', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField()),
                ('tread_depth', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('working_hours', models.IntegerField()),
                ('condition_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField()),
                ('requires_immediate_attention', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tire.tire')),
            ],
            options={
                'db_table': 'technical_reports',
            },
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_repairs', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tire.tire')),
            ],
            options={
                'db_table': 'repair_requests',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('WORKING_HOURS', 'Working Hours Exceeded'), ('TREAD_DEPTH', 'Low Tread Depth'), ('WARRANTY_EXPIRY', 'Warranty Near Expiration')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tire.tire')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='TireModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('compound', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tire.tirecategory')),
            ],
            options={
                'unique_together': {('brand', 'pattern', 'size')},
            },
        ),
        migrations.AddField(
            model_name='tire',
            name='tire_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tire.tiremodel'),
        ),
        migrations.CreateModel(
            name='TireOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PRE_ORDER', 'Pre-Order'), ('SUPPLIER_ORDER', 'Ordered from Supplier'), ('OCEAN_SHIPPING', 'Ocean Shipping'), ('IN_CUSTOMS', 'In Customs'), ('CUSTOMS_CLEARED', 'Customs Cleared'), ('SUPPLIER_WAREHOUSE', 'In Supplier Warehouse'), ('AWAITING_SERIAL_NUMBERS', 'Awaiting Serial Numbers'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('SHIPPING_TO_CUSTOMER', 'Shipping to Customer'), ('DELIVERED', 'Delivered to Customer')], default='PRE_ORDER', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TireOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cleared_quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tire.tireorder')),
                ('tire_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tire.tiremodel')),
            ],
        ),
        migrations.AddField(
            model_name='tire',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tire.tireorderitem'),
        ),
        migrations.CreateModel(
            name='TireSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('aspect_ratio', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('standard_description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tire_sizes',
                'unique_together': {('width', 'aspect_ratio', 'diameter')},
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('thumbnail_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='tire.trainingcategory')),
            ],
            options={
                'db_table': 'trainings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_training_requests', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tire.trainingcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_warranties', to=settings.AUTH_USER_MODEL)),
                ('tire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tire.tire')),
            ],
            options={
                'db_table': 'warranties',
            },
        ),
    ]
