# Generated by Django 5.1.4 on 2024-12-31 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tire Categories',
                'db_table': 'tire_categories',
            },
        ),
        migrations.AddField(
            model_name='tire',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tire',
            name='compound',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tire',
            name='pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tire',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tire',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tire.tirecategory'),
        ),
    ]
