# Generated by Django 5.1.4 on 2025-02-11 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiremodel',
            name='initial_tread_depth',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
