# Generated by Django 5.1.4 on 2024-12-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0002_tirecategory_tire_brand_tire_compound_tire_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
